language: node_js
sudo: required
dist: trusty

git:
  depth: 10

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

cache:
  directories:
    - node_modules

before_install:
  - chmod +x ./scripts/travis-after-success.sh
  - npm i -g npm@6.0.1
  - npm install -g @blackbaud/skyux-cli

install:
  - npm install
  - npm install blackbaud/skyux-builder-config

script:
  - npm run test:ci

after_script:
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/library-after-script.sh)

after_success:
  - ./scripts/travis-after-success.sh
